#pragma once
#include "t2_.h"
#include "t2_phys.h"
#include "t2_scene.h"
#include "t2_sceneitem_bucket.h"
#include "t2_sceneitem_door.h"
#include "t2_sceneitem_player.h"
#include "t2_sceneitem_wall.h"
#include "t2_sceneitem_exploder.h"
