#pragma once
#include "t5_.h"
#include "t5_phys.h"
#include "t5_scene.h"
#include "t5_sceneitem_bucket.h"
#include "t5_sceneitem_door.h"
#include "t5_sceneitem_player.h"
#include "t5_sceneitem_wall.h"
#include "t5_sceneitem_exploder.h"
